[mypy]
ignore_missing_imports = False

[mypy-rdkit.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-chemprop.*]
ignore_missing_imports = True

[mypy-faerun.*]
ignore_missing_imports = True

[mypy-tmap.*]
ignore_missing_imports = True

[mypy-jmespath.*]
ignore_missing_imports = True
